cv_folds: 10
scoring: neg_mean_absolute_error
n_trials: 30
timeout: 1200

early_stopping_rounds: 10

models:
  xgboost:
    n_estimators: [300, 500, 600]
    max_depth: [8, 10, 12]
    learning_rate: [0.01, 0.02, 0.05,]
    subsample: [0.7, 0.8]
    colsample_bytree: [0.9]
    random_state: [15, 42, 100]
    tree_method: "hist"
    predictor: "auto"
    grow_policy: "depthwise"
